package cc.cherr.shelldeck.backup

import cc.cherr.shelldeck.data.ProxyRecord
import cc.cherr.shelldeck.data.HostRecord
import cc.cherr.shelldeck.data.IdentityRecord
import cc.cherr.shelldeck.ssh.startupCommandLine
import java.io.*

/** Private material is never included in autogenerated toString/equals or persisted unencrypted. */
class BackupIdentity(val record: IdentityRecord, val privateKey: ByteArray)
class BackupProxy(val record: ProxyRecord, val credentials: ByteArray)
class BackupData(val identities: List<BackupIdentity>, val hosts: List<HostRecord>, val settings: String, val proxies: List<BackupProxy> = emptyList()) : AutoCloseable {
    override fun close() { identities.forEach { it.privateKey.fill(0) }; proxies.forEach { it.credentials.fill(0) } }
}
internal class WipingBuffer(private val limit: Int) : ByteArrayOutputStream() {
    private fun reserve(extra: Int) {
        require(extra >= 0 && extra <= limit - count)
        if (count + extra > buf.size) {
            val previous = buf
            buf = previous.copyOf(maxOf(count + extra, minOf(limit, previous.size * 2)))
            previous.fill(0)
        }
    }
    override fun write(value: Int) { reserve(1); buf[count++] = value.toByte() }
    override fun write(bytes: ByteArray, offset: Int, length: Int) {
        require(offset >= 0 && length >= 0 && offset <= bytes.size - length)
        reserve(length); System.arraycopy(bytes, offset, buf, count, length); count += length
    }
    override fun close() { buf.fill(0); reset() }
}
fun readBackupFile(input: InputStream): ByteArray = WipingBuffer(BackupCrypto.MAX_FILE).use { output ->
    val buffer = ByteArray(8192)
    try {
        while (true) { val count = input.read(buffer); if (count < 0) break; output.write(buffer, 0, count) }
        output.toByteArray()
    } finally { buffer.fill(0) }
}

/** Length-prefixed binary payload avoids immutable Base64/String copies of private keys. */
object BackupCodec {
    private const val MAX_TEXT = 16 * 1024
    private const val MAX_SETTINGS = 1024 * 1024
    private const val MAX_KEY = 256 * 1024
    fun encode(data: BackupData): ByteArray {
        validate(data)
        return WipingBuffer(BackupCrypto.MAX_PLAINTEXT).use { buffer ->
            val out = DataOutputStream(buffer)
            out.writeInt(3); out.text(data.settings, MAX_SETTINGS)
            out.writeInt(data.identities.size)
            data.identities.forEach { entry ->
                val key = entry.record
                out.text(key.id); out.text(key.label); out.text(key.algorithm); out.text(key.fingerprint)
                out.writeBoolean(key.publicKey != null); key.publicKey?.let { out.text(it) }
                out.blob(entry.privateKey, MAX_KEY)
            }
            out.writeInt(data.hosts.size)
            data.hosts.forEach { host ->
                out.text(host.id); out.text(host.label); out.text(host.hostname); out.writeInt(host.port); out.text(host.username)
                out.writeBoolean(host.identityId != null); host.identityId?.let { out.text(it) }
                out.writeBoolean(host.jumpHostId != null); host.jumpHostId?.let { out.text(it) }
                out.writeBoolean(host.proxyId != null); host.proxyId?.let { out.text(it) }
                out.text(host.startupCommand); out.writeBoolean(host.favorite); out.writeLong(host.lastUsedAt)
            }
            out.writeInt(data.proxies.size)
            data.proxies.forEach { entry ->
                val p = entry.record
                out.text(p.id); out.text(p.label); out.text(p.hostname); out.writeInt(p.port)
                out.writeBoolean(p.remoteDns); out.writeBoolean(p.authenticated); out.blob(entry.credentials, 511)
            }
            out.flush(); buffer.toByteArray()
        }
    }
    fun decode(bytes: ByteArray): BackupData {
        require(bytes.size <= BackupCrypto.MAX_PLAINTEXT)
        val keys = mutableListOf<BackupIdentity>()
        val proxies = mutableListOf<BackupProxy>()
        try {
            val input = DataInputStream(ByteArrayInputStream(bytes))
            val version = input.readInt(); require(version in 1..3)
            val settings = input.text(MAX_SETTINGS)
            repeat(input.readInt().also { require(it in 0..1000) }) {
                val record = IdentityRecord().apply {
                    id = input.text(); label = input.text(); algorithm = input.text(); fingerprint = input.text()
                    publicKey = if (input.readBoolean()) input.text() else null
                }
                keys.add(BackupIdentity(record, input.blob(MAX_KEY)))
            }
            val hosts = List(input.readInt().also { require(it in 0..5000) }) {
                HostRecord().apply {
                    id = input.text(); label = input.text(); hostname = input.text(); port = input.readInt(); username = input.text()
                    identityId = if (input.readBoolean()) input.text() else null
                    jumpHostId = if (version >= 2 && input.readBoolean()) input.text() else null
                    proxyId = if (version >= 3 && input.readBoolean()) input.text() else null
                    startupCommand = input.text(); favorite = input.readBoolean(); lastUsedAt = input.readLong()
                }
            }
            if (version >= 3) repeat(input.readInt().also { require(it in 0..1000) }) {
                val record = ProxyRecord().apply {
                    id = input.text(); label = input.text(); hostname = input.text(); port = input.readInt()
                    remoteDns = input.readBoolean(); authenticated = input.readBoolean()
                }
                proxies.add(BackupProxy(record, input.blob(511)))
            }
            require(input.available() == 0)
            return BackupData(keys, hosts, settings, proxies).also(::validate)
        } catch (failure: Exception) { keys.forEach { it.privateKey.fill(0) }; proxies.forEach { it.credentials.fill(0) }; throw failure }
    }
    private fun validate(data: BackupData) {
        require(data.identities.size <= 1000 && data.hosts.size <= 5000)
        require(data.proxies.size <= 1000)
        val proxyIds = data.proxies.map { it.record.id }.toSet()
        require(proxyIds.size == data.proxies.size)
        data.proxies.forEach {
            cc.cherr.shelldeck.proxy.validateProxy(it.record)
            if (it.record.authenticated) cc.cherr.shelldeck.proxy.ProxyCredentials.decode(it.credentials).close()
            else require(it.credentials.isEmpty())
        }
        val ids = data.identities.map { it.record.id }.toSet()
        require(ids.size == data.identities.size && data.hosts.map { it.id }.toSet().size == data.hosts.size)
        data.identities.forEach {
            require(it.record.id.isNotBlank() && it.record.label.isNotBlank() && it.privateKey.size in 1..MAX_KEY)
            require(it.record.fingerprint.startsWith("SHA256:") && it.record.algorithm.isNotBlank())
        }
        data.hosts.forEach {
            require(it.id.isNotBlank() && it.label.isNotBlank() && it.hostname.isNotBlank() && it.username.isNotBlank())
            require(it.proxyId == null || it.proxyId in proxyIds)
            require(it.port in 1..65535 && it.lastUsedAt >= 0 && (it.identityId == null || it.identityId in ids))
            require(it.hostname.none { char -> char.isWhitespace() || char == '/' || char.isISOControl() })
            cc.cherr.shelldeck.ssh.jumpRoute(it) { id -> data.hosts.firstOrNull { host -> host.id == id } }
            startupCommandLine(it.startupCommand).fill(0)
        }
    }
    private fun DataOutputStream.blob(bytes: ByteArray, max: Int) { require(bytes.size <= max); writeInt(bytes.size); write(bytes) }
    private fun DataOutputStream.text(value: String, max: Int = MAX_TEXT) { blob(value.toByteArray(Charsets.UTF_8), max) }
    private fun DataInputStream.blob(max: Int): ByteArray {
        val size = readInt(); require(size in 0..max && size <= available())
        return ByteArray(size).also { readFully(it) }
    }
    private fun DataInputStream.text(max: Int = MAX_TEXT): String = blob(max).toString(Charsets.UTF_8)
}
